title: rajatrao13  
subtitle: rajatrao13 | OSCP
description: ># this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://rajatrao-13.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: About-Me
      url : /about


# Edit these details

author_logo: profile.png
author: Rajat Rao
author_bio: Hi, my name is Rajat Rao. My professional IT career exapnds over 3 years as a Cyber Security Consultant.I am OSCP certified and I am an active user on HackTheBox. This site focuses on Information Security blogs and writeups.
author_email: "rajatrao13@gmail.com"
author_location: India
author_website_url: "https://rajatrao13.github.io/"
typewrite-text: Cyber Security Specialist!

author_work_experiences:
            - company_name: Ernst & Young
              company_logo: EY.png
              company_url: https://www.ey.com/en_us
              designation: Cyber Security Consultant
              description: Worked on security projects dealing with domains such as Mobile Security, Thick Client Security, API Security, Network Infrastructure Security, IoT Security, End-Point Review and more
              visibility: true
            - company_name: AMBC Technologies
              company_logo: AMBC.png
              company_url: https://www.ambconline.com/
              designation: External Cyber Security Consultant
              description: Works as a Cyber Security Consultant with a role of honing the IT Security Services and implementation of new security assessment methodologies to multiple domains.
              visibility: true
              
author_education_details:
              - college_logo: DJ.png
                college_name: Dwarkadas Jivanlal Sanghvi College of Engineering
                college_url: http://www.djsce.ac.in/
                college_degree: Information technology
                description: Bachelor of Engineering
                visibility: true


# social links
twitter_username: johndoe
github_username:  sujaykundu777
facebook_username: rajatarao@yahoo.com
linkedin_username: rajatrao13
behance_username: johndoe
instagram_username: rajatrao13@gmail.com
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
